[package]
name = "packed-semver"
version = "0.1.0"
authors.workspace = true
edition = "2024"

[[bin]]
name = "packed-semver-calculator"
path = "src/bin/calculator.rs"

[features]
statistics = []

[dependencies]
rkyv = "0.8.10"
serde = "1"
thiserror = "2"
